AWSTemplateFormatVersion: "2010-09-09"
Description: DMS Replication Instance, Endpoint, and Task Example

Parameters:
  TargetBucketName:
    Type: String
    Description: Name of taget S3 bucket

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs where the DMS Subnet Group will be created

Resources:

  VZCDMSReplicationSubnetGroup:
    Type: "AWS::DMS::ReplicationSubnetGroup"
    Properties:
      ReplicationSubnetGroupIdentifier: VZCDMSReplicationSubnetGroup
      ReplicationSubnetGroupDescription: DMS replication subnet group
      SubnetIds: !Ref SubnetIds

  ReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      ReplicationInstanceIdentifier: VZCImportReplicationInstance
      AllocatedStorage: 100
      ReplicationInstanceClass: dms.r6i.xlarge
      VpcSecurityGroupIds:
        - sg-04d00f2f1f8e0bad6 # Replace with your security group ID(s)
      ReplicationSubnetGroupIdentifier: !Ref VZCDMSReplicationSubnetGroup # Replace with your subnet group ID
      Tags:
        - Key: Name
          Value: DMSReplicationInstance

  SourceEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: MSSQLSourceEndpoint
      EndpointType: source
      EngineName: sqlserver
      ServerName: ec2-sql-server
      Port: 1433
      DatabaseName: VerizonConnect
      Username: '{{resolve:secretsmanager:source-mssql:SecretString:username}}'
      Password: '{{resolve:secretsmanager:source-mssql:SecretString:username}}'
      MySqlSettings:
        SecretsManagerAccessRoleArn: arn:aws:iam::****:role/allow-dms-access-secrets-manager


  TargetEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: S3TargetEndpoint
      EndpointType: target
      EngineName: s3
      S3Settings:
        BucketName: !Ref TargetBucketName
        BucketFolder: raw
        CompressionType: GZIP
        EnableStatistics: true
        DataFormat: parquet
        MaxFileSize: 512000
        ServiceAccessRoleArn: arn:aws:iam::*****:role/dms-s3-access
      Tags:
        - Key: Name
          Value: MyTargetEndpoint 


  MigrationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      SourceEndpointArn: !Ref SourceEndpoint
      TargetEndpointArn: !Ref TargetEndpoint
      ReplicationInstanceArn: !Ref ReplicationInstance
      MigrationType: full-load
      TableMappings: |
        {
          "rules": [
            {
              "rule-type": "selection",
              "rule-id": "029219233",
              "rule-name": "029219233",
              "object-locator": {
                  "schema-name": "dbo",
                  "table-name": "tbl_DTCEvents"
              },
              "rule-action": "include",
              "filters": []
            },
          ]
        }

Outputs:
  ReplicationInstanceArn:
    Description: The ARN of the DMS Replication Instance
    Value: !Ref ReplicationInstance
