        Type: AWS::DMS::Endpoint
        Properties:
          EndpointIdentifier: !Join ['--', [!Ref Environment, !Ref SourceEndpointName]]
          EndpointType: source
          EngineName: !Ref SourceEndpointDatabaseEngineName
          ServerName: !Ref SourceEndpointServerName
          Port: !Ref SourceEndpointDatabasePort
          DatabaseName: !If [ HasSourceDatabaseName, !Ref SourceDatabaseName, !Ref "AWS::NoValue" ]
          Username: !Join
            - ":"
            - - "{{resolve:secretsmanager"
              - !Ref SourceEndpointDatabaseCredentialsSecret
              - "secret-string"
              - "username}}"
