

Parameters:

  ServerNames: 
    Type: CommaDelimitedList
    Default: server1,server2,...,server16

Resources:

  DMSEndpoint1:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: !Join ["-", [!Ref ServerNames, "-endpoint-1"]]
      ServerName: !Ref ServerNames
      DatabaseName: db1
      
    Fn::ForEach: !Ref ServerNames

  DMSEndpoint2:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: !Join ["-", [!Ref ServerNames, "-endpoint-2"]]
      ServerName: !Ref ServerNames
      DatabaseName: db2

    Fn::ForEach: !Ref ServerNames
