Resources:
  MyStepFunction:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: MyStateMachine
      DefinitionString:
        Fn::Sub:
          - |-
            {
              "Comment": "A state machine that orchestrates a Lambda function and an ECS task.",
              "StartAt": "LambdaFunctionState",
              "States": {
                "LambdaFunctionState": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke",
                  "Parameters": {
                    "FunctionName": "${LambdaFunction}",
                    "Payload": {
                      "Input.$": "$"
                    }
                  },
                  "Next": "ECSTaskState"
                },
                "ECSTaskState": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::ecs:runTask.sync",
                  "Parameters": {
                    "LaunchType": "FARGATE",
                    "Cluster": "${EcsCluster}",
                    "TaskDefinition": "${EcsTaskDefinition}",
                    "Overrides": {
                      "ContainerOverrides": [
                        {
                          "Name": "ContainerName",
                          "Environment": [
                            {
                              "Name": "INPUT",
                              "Value.$": "$.Payload"
                            }
                          ]
                        }
                      ]
                    }
                  },
                  "End": true
                }
              }
            }
          - LambdaFunction: !GetAtt MyLambdaFunction.Arn
            EcsCluster: !Ref MyECSCluster
            EcsTaskDefinition: !Ref MyECSTaskDefinition
      RoleArn: !GetAtt MyExecutionRole.Arn

  MyExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: MyExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                  - 'ecs:RunTask'
                Resource: '*'
